config/routes.rb
Foundation::Application.routes.draw do |map|

  namespace :admin do
    resources :users
  end
  
  devise_for :users

  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable, :timeoutable and :oauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    # testing object and session caching via Dalli
    @session_time = session[:foo] ||= Time.now
    @cache_time = Rails.cache.fetch('current_time', :expires_in => 1.day) do
      Time.now
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_filter :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
#  before_filter :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    # testing object and session caching via Dalli
    @session_time = session[:foo] ||= Time.now
    @cache_time = Rails.cache.fetch('current_time', :expires_in => 1.day) do
      Time.now
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_form.html.erb
  <div class="group">
    <%= f.label :email, t("activerecord.attributes.user.email", :default => "Email"), :class => :label %>
    <%= f.text_field :email, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :password, t("activerecord.attributes.user.encrypted_password", :default => "Password"), :class => :label %>
    <%= f.text_field :password, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :password_confirmation, t("activerecord.attributes.user.password_confirmation", :default => "Password Confirmation"), :class => :label %>
    <%= f.text_field :password_confirmation, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :sign_in_count, t("activerecord.attributes.user.sign_in_count", :default => "Sign in count"), :class => :label %>
    <%= f.text_field :sign_in_count, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :current_sign_in_at, t("activerecord.attributes.user.current_sign_in_at", :default => "Current sign in at"), :class => :label %>
    <%= f.datetime_select :current_sign_in_at, :class => 'datetime_select' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :last_sign_in_at, t("activerecord.attributes.user.last_sign_in_at", :default => "Last sign in at"), :class => :label %>
    <%= f.datetime_select :last_sign_in_at, :class => 'datetime_select' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :current_sign_in_ip, t("activerecord.attributes.user.current_sign_in_ip", :default => "Current sign in ip"), :class => :label %>
    <%= f.text_field :current_sign_in_ip, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :last_sign_in_ip, t("activerecord.attributes.user.last_sign_in_ip", :default => "Last sign in ip"), :class => :label %>
    <%= f.text_field :last_sign_in_ip, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>  
  <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}") + " " + t("web-app-theme.cancel", :default => "Cancel"), admin_users_path, :class => "button" %> 
</div>

app/views/admin/users/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/admin/users/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_user_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> User</h2>
    <div class="inner">
      <%= form_for @user, :url => admin_user_path(@user), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/users/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Users</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @users.each do |user| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= user.id %>
          </td>
                    <td>
            <%= link_to user.email, admin_user_path(user) %>
          </td>
                    <td>
            <%= user.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_user_path(user) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_user_path(user) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/users/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  User</h2>
    <div class="inner">
      <%= form_for :user, :url => admin_users_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/users/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_user_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>:</b>
          <%= @user.email %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.user.encrypted_password", :default => t("activerecord.labels.encrypted_password", :default => "Encrypted password")) %>:</b>
          <%= @user.encrypted_password %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.user.password_salt", :default => t("activerecord.labels.password_salt", :default => "Password salt")) %>:</b>
          <%= @user.password_salt %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.user.reset_password_token", :default => t("activerecord.labels.reset_password_token", :default => "Reset password token")) %>:</b>
          <%= @user.reset_password_token %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.user.remember_token", :default => t("activerecord.labels.remember_token", :default => "Remember token")) %>:</b>
          <%= @user.remember_token %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.user.remember_created_at", :default => t("activerecord.labels.remember_created_at", :default => "Remember created at")) %>:</b>
          <%= @user.remember_created_at %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.user.sign_in_count", :default => t("activerecord.labels.sign_in_count", :default => "Sign in count")) %>:</b>
          <%= @user.sign_in_count %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.user.current_sign_in_at", :default => t("activerecord.labels.current_sign_in_at", :default => "Current sign in at")) %>:</b>
          <%= @user.current_sign_in_at %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.user.last_sign_in_at", :default => t("activerecord.labels.last_sign_in_at", :default => "Last sign in at")) %>:</b>
          <%= @user.last_sign_in_at %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.user.current_sign_in_ip", :default => t("activerecord.labels.current_sign_in_ip", :default => "Current sign in ip")) %>:</b>
          <%= @user.current_sign_in_ip %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.user.last_sign_in_ip", :default => t("activerecord.labels.last_sign_in_ip", :default => "Last sign in ip")) %>:</b>
          <%= @user.last_sign_in_ip %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_user_path(@user), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_user_path(@user), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/home/index.html.erb
<h3>Welcome Home!</h3>
<p>
  This is your home page.
</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foundation</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <%= render :partial => 'shared/header' %>
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
    <%= render :partial => 'shared/footer' %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Foundation</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <%= render :partial => 'shared/header' %>
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>
    <%= render :partial => 'shared/footer' %>
  </div>
  <%= render :partial => 'shared/ga' %>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foundation</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="box">
      <%= yield %>            
    </div>
  </div>
</body>
</html>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foundation</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="box">
      <%= yield %>            
    </div>
  </div>
</body>
</html>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="block">
    <p>Copyright &copy; <%= Time.now.year %> Acme Co.</p>
  </div>
</div>

app/views/shared/_ga.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script>
  var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
  (function(d, t) {
  var g = d.createElement(t),
      s = d.getElementsByTagName(t)[0];
  g.async = true;
  g.src = '//www.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g, s);
  })(document, 'script');
</script>

app/views/shared/_header.html.erb
<div id="header">
  <h1><a href="/">Foundation</a></h1>
  <div id="user-navigation">
    <ul class="wat-cf">
      <li><a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a></li>
      <li><a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a></li>
      <% if user_signed_in? -%>
      <li><%= link_to t("web-app-theme.logout", :default => "Logout"), destroy_user_session_path, :class=>"logout" %></li>
      <% else -%>
      <li><%= link_to t("web-app-theme.login", :default => "Login"), new_user_session_path, :class=>"login" %></li>
      <% end -%>
    </ul>
  </div>
  <div id="main-navigation">
    <ul class="wat-cf"></ul>
  </div>
</div>